### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by YourMCGeek**
Original README.md can be found on the wiki.

### CODE REVIEW

**Comment by johnfg10** [comment]
we could do with a bit more text then that :P

**Comment by YourMCGeek** [comment]
Do we NEED more text though since really only we are looking at it?

**Comment by johnfg10** [comment]
alot of that text is ok :P

**Comment by johnfg10** [comment]
features for example is good

**Comment by YourMCGeek** [comment]
There :)

**Comment by johnfg10** [comment]
ty :)

**Pull request merged**
